# Node docker image with Cypress and Chrome pre-installed
image: cypress/browsers:node12.0.0-chrome73

# Pipeline
stages:
  - install
  - build
  - test
  - deploy

# Jobs 

# NEW
variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
   CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
   key:
     files:
        - package.json
   paths:
      - .npm
      - cache/Cypress
      - node_modules
# END NEW

install_dependencies:
  stage: install
  script:
    - npm ci

bundle_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    
e2etest:    
  stage: test
  only:
    - staging
    - master
  before_script:
    - npm install -g http-server
    - npm install cypress
  script:
    # start the server in the background
    - npm run start:ci


fetch: 
  stage: build
  script:
    - echo "=====start build======"
    - npm install
    - npm run build
    - echo "=====end build======"
  only:
    - master
  artifacts: 
    expire_in: 2 week
    paths: 
      - dist/
    
deploy-static:
  stage: deploy
  script:
    - echo "=====start deploy======"
    - echo "=====end deploy======"
  only:
    - master